import { Lora } from "next/font/google";
import Image from "next/image";
import background from "../public/assets/bg.png";
import "./globals.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import FooterPage from "@/components/FooterPage";

// const jetbrainsMono = JetBrains_Mono({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
//   variable: "--font-jetbrainsMono",
// });

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} z-[-2] h-full w-full absolute inset-0 bg-[linear-gradient(to_right,#25283b22_1px,transparent_1px),linear-gradient(to_bottom,#25283b22_1px,transparent_1px)] bg-[size:100px_100px]`}
      >
        <section className="relative w-full bg-transparent">
          <div className="absolute mt-[6.3rem] z-[-1]">
            <Image src={background} alt="bg img" className="w-full" />
          </div>
          <Header />
          <StairTransition />
          <PageTransition>{children}</PageTransition>
        </section>
        <FooterPage />
      </body>
    </html>
  );
}
